// ---- SmartESH v60: Learning Center Hotfix (Grammar / Vocabulary / Phrasal Verbs / Idioms) ----
(function(){
  const lessons = [
    {id:'g-tenses',type:'grammar',title:'Tenses Overview',subtitle:'Present • Past • Future • Perfect',level:'A2–B2',exam:'High',mn:'Үйл явдал хэзээ болсон, үргэлжилж байгаа эсэх, үр дүн нь одоотой холбоотой эсэхийг зөв ялгах нь ЭЕШ-ийн grammar хэсгийн суурь.',formula:['Present Simple: S + V1(s/es)','Present Continuous: am/is/are + V-ing','Past Simple: V2 / did + V1','Present Perfect: have/has + V3'],examples:['She goes to school every day. — Тэр өдөр бүр сургуульдаа явдаг.','She is studying now. — Тэр одоо хичээллэж байна.','I have finished my homework. — Би даалгавраа дуусгасан.'],tip:'Time expression-ээ эхэлж хар: every day, now, yesterday, since/for, already, yet.',mistake:'since + эхлэх цэг; for + хугацаа.'},
    {id:'g-passive',type:'grammar',title:'Passive Voice',subtitle:'be + V3',level:'A2–B2',exam:'High',mn:'Үйлдлийг хэн хийснээс илүү үйлдэлд өртсөн зүйл чухал үед passive хэрэглэнэ.',formula:['Present: am/is/are + V3','Past: was/were + V3','Perfect: have/has been + V3','Modal: modal + be + V3'],examples:['English is spoken worldwide. — Англи хэл дэлхий даяар ярьдаг.','The bridge was built in 2010. — Гүүр 2010 онд баригдсан.'],tip:'Active өгүүлбэрийн object passive өгүүлбэрийн subject болно.',mistake:'Passive-д үндсэн үйл үг V3 хэлбэртэй байна.'},
    {id:'g-modals',type:'grammar',title:'Modal Verbs',subtitle:'can • must • should • may • might',level:'A2–B2',exam:'High',mn:'Чадвар, зөвлөгөө, үүрэг, магадлал, зөвшөөрлийг modal verb-ээр илэрхийлнэ.',formula:['modal + V1','must not = хориг','do not have to = шаардлагагүй'],examples:['You should see a doctor. — Эмчид үзүүлбэл зохино.','You must wear a seat belt. — Бүсээ заавал зүүнэ.'],tip:'Modal-ийн дараа to биш шууд V1 орно. Exception: have to, ought to.',mistake:'mustn’t ба don’t have to хоёр өөр утгатай.'},
    {id:'g-conditionals',type:'grammar',title:'Conditionals',subtitle:'Zero • First • Second • Third',level:'A2–B2',exam:'High',mn:'Нөхцөл ба үр дүнгийн бодит, боломжит, төсөөллийн болон өнгөрсөн харамслыг ялгана.',formula:['Zero: If + present, present','First: If + present, will + V1','Second: If + past, would + V1','Third: If + had + V3, would have + V3'],examples:['If it rains, we will stay home.','If I were you, I would study more.','If she had left earlier, she would have caught the bus.'],tip:'If-clause дотор first conditional-д will ерөнхийдөө хэрэглэдэггүй.',mistake:'Second conditional-д I/he/she-тэй were хэрэглэж болно.'},
    {id:'g-wish',type:'grammar',title:'Wish / If only',subtitle:'present regret • past regret',level:'B1–B2',exam:'Medium',mn:'Одоогийн бодит бус хүсэл болон өнгөрсөн харамслыг илэрхийлнэ.',formula:['wish + past simple = одоогийн хүсэл','wish + past perfect = өнгөрсөн харамсал','wish + would = өөрчлөгдөхийг хүсэх'],examples:['I wish I knew the answer. — Хариултыг мэддэг ч болоосой.','She wishes she had studied harder. — Илүү сайн хичээллэсэн ч болоосой.'],tip:'Одоогийн хүсэлд past хэлбэр орсон ч утга нь present байж болно.',mistake:'wish + will биш, ихэнхдээ wish + would.'},
    {id:'g-reported',type:'grammar',title:'Reported Speech',subtitle:'statements • questions • commands',level:'B1–B2',exam:'High',mn:'Хэн нэгний хэлснийг шууд бус хэлбэрээр дамжуулахдаа tense, pronoun, time expression өөрчлөгдөнө.',formula:['say + (that) clause','tell + person + clause','asked + if/whether / wh-word'],examples:['“I am tired.” → She said that she was tired.','“Where do you live?” → He asked me where I lived.'],tip:'Reported question-д асуултын word order биш statement word order хэрэглэнэ.',mistake:'tell-ийн дараа хүн заавал орно: tell me, tell him.'},
    {id:'g-gerund',type:'grammar',title:'Gerund & Infinitive',subtitle:'V-ing vs to + V1',level:'B1–B2',exam:'High',mn:'Зарим үйл үгийн дараа V-ing, заримын дараа to + V1, заримын дараа хоёулаа өөр утгатай ордог.',formula:['enjoy/avoid/finish + V-ing','want/decide/hope + to V1','make/let + object + V1'],examples:['I enjoy reading.','She decided to study abroad.','My parents let me go out.'],tip:'stop doing = үйлдлээ болих; stop to do = өөр зүйл хийхээр зогсох.',mistake:'suggest + V-ing; suggest to do биш.'},
    {id:'g-relative',type:'grammar',title:'Relative Clauses',subtitle:'who • which • that • whose • where',level:'B1–B2',exam:'High',mn:'Нэр үгийг нэмэлт мэдээллээр тодорхойлохдоо relative pronoun ашиглана.',formula:['who = хүн','which = зүйл','whose = эзэмшил','where = газар'],examples:['The girl who won the prize is my friend.','This is the book that I told you about.'],tip:'Comma-тай non-defining clause-д that хэрэглэдэггүй.',mistake:'whose-ийн дараа noun орно: whose car, whose idea.'},
    {id:'g-articles',type:'grammar',title:'Articles',subtitle:'a • an • the • zero article',level:'A2–B1',exam:'High',mn:'Тодорхой бус нэг зүйлд a/an, тодорхой эсвэл өмнө дурдсан зүйлд the, ерөнхий plural/uncountable-д articleгүй хэрэглэнэ.',formula:['a + consonant sound','an + vowel sound','the + specific/unique noun'],examples:['I saw a dog. The dog was friendly.','She is an honest person.'],tip:'a/an сонгохдоо үсгийг биш авиаг хар: an hour, a university.',mistake:'languages, school subjects-ийн өмнө ерөнхийдөө articleгүй.'},
    {id:'g-quantifiers',type:'grammar',title:'Quantifiers',subtitle:'some • any • much • many • few • little',level:'A2–B1',exam:'High',mn:'Countable болон uncountable noun-тай тохирох хэмжээг илэрхийлэх үгийг зөв сонгоно.',formula:['many/few + countable plural','much/little + uncountable','a lot of + both'],examples:['There are a few students outside.','We have little time left.'],tip:'few/little = бараг байхгүй; a few/a little = бага боловч бий.',mistake:'information, advice, furniture — uncountable.'},
    {id:'g-comparison',type:'grammar',title:'Comparatives & Superlatives',subtitle:'-er • more • the most • as...as',level:'A2–B1',exam:'Medium',mn:'Хоёр болон олон зүйлсийн ялгаа, ижил түвшнийг харьцуулна.',formula:['short adj: -er / -est','long adj: more / most','as + adj + as'],examples:['This test is easier than the last one.','She is the most careful student in the class.'],tip:'much/far/a lot + comparative: much better, far more difficult.',mistake:'more easier гэж давхар comparative бүү хэрэглэ.'},
    {id:'g-adjadv',type:'grammar',title:'Adjectives & Adverbs',subtitle:'careful vs carefully',level:'A2–B1',exam:'Medium',mn:'Adjective нь noun-ыг, adverb нь verb/adjective/adverb-ийг тодорхойлно.',formula:['be/seem/look + adjective','action verb + adverb'],examples:['She is a careful driver.','She drives carefully.'],tip:'fast, hard, late зэрэг нь -lyгүй adverb байж болно.',mistake:'hardly = бараг үгүй; hard = шаргуу.'},
    {id:'g-prepositions',type:'grammar',title:'Prepositions',subtitle:'time • place • movement • dependent',level:'A2–B2',exam:'High',mn:'in/on/at болон verb/adjective-ийн дараах тогтсон угтвар үгс ЭЕШ-д түгээмэл шалгагдана.',formula:['at + exact time','on + day/date','in + month/year/period'],examples:['at 7 o’clock','on Monday','in September','interested in science'],tip:'Үгийг дангаар бус collocation-аар цээжил: depend on, good at, afraid of.',mistake:'arrive in + city/country; arrive at + small place.'},
    {id:'g-conjunctions',type:'grammar',title:'Conjunctions & Linkers',subtitle:'although • despite • because • therefore',level:'B1–B2',exam:'High',mn:'Шалтгаан, эсрэгцэл, үр дүн, нэмэлт санааг зөв холбоно.',formula:['because + clause','because of + noun','although + clause','despite/in spite of + noun/V-ing'],examples:['Although it was cold, we went out.','Despite the rain, the match continued.'],tip:'because vs because of; although vs despite хэлбэрийг ялга.',mistake:'despite of гэж бичихгүй.'},
    {id:'g-sva',type:'grammar',title:'Subject–Verb Agreement',subtitle:'singular vs plural verb',level:'A2–B2',exam:'High',mn:'Subject-ийн жинхэнэ head noun-ийг олж verb-ийн singular/plural хэлбэрийг тааруулна.',formula:['each/every/everyone + singular verb','a number of + plural','the number of + singular'],examples:['Everyone is ready.','A number of students are absent.'],tip:'Subject ба verb-ийн дунд олон үг орсон ч гол subject-ээ ол.',mistake:'Neither of the answers is correct.'},
    {id:'g-questions',type:'grammar',title:'Questions & Question Tags',subtitle:'do/does/did • auxiliaries • tags',level:'A2–B1',exam:'Medium',mn:'Асуулт үүсгэхдээ auxiliary-г subject-ийн өмнө байрлуулна. Tag question нь үндсэн өгүүлбэрийн эсрэг polarity-тай.',formula:['Wh + auxiliary + S + V?','positive statement + negative tag','negative statement + positive tag'],examples:['Where does he live?','You are ready, aren’t you?'],tip:'Who subject болж байвал do/does ихэвчлэн хэрэггүй: Who called you?',mistake:'Let’s ... , shall we?'},
    {id:'g-causative',type:'grammar',title:'Causative',subtitle:'have/get something done',level:'B1–B2',exam:'Medium',mn:'Өөр хүнээр ажил хийлгэснийг have/get + object + V3 хэлбэрээр илэрхийлнэ.',formula:['have + object + V3','get + object + V3'],examples:['I had my hair cut yesterday.','We are getting the car repaired.'],tip:'Subject өөрөө үйлдлийг хийгээгүй.',mistake:'have my hair cut ≠ cut my hair myself.'},
    {id:'g-participles',type:'grammar',title:'Participles',subtitle:'-ed vs -ing adjectives',level:'B1–B2',exam:'Medium',mn:'-ing adjective нь мэдрэмж төрүүлж буй зүйл, -ed adjective нь тухайн мэдрэмжийг авч буй хүнийг дүрсэлнэ.',formula:['interesting = сонирхол төрүүлдэг','interested = сонирхож байгаа'],examples:['The film was boring.','I was bored during the film.'],tip:'Thing → often -ing; person’s feeling → often -ed.',mistake:'I am interesting гэвэл “би бусдад сонирхолтой” гэсэн утга.'},
    {id:'g-inversion',type:'grammar',title:'Inversion',subtitle:'Never • Rarely • Not only',level:'B2',exam:'Advanced',mn:'Сөрөг утгатай adverb өгүүлбэрийн эхэнд орвол auxiliary + subject гэсэн урвуу бүтэц ордог.',formula:['Never + auxiliary + S + V','Not only + auxiliary + S + V, but also...'],examples:['Never have I seen such a view.','Rarely does he arrive late.'],tip:'Advanced transformation асуултад түгээмэл.',mistake:'Negative opener-ийн дараа statement word order бүү хэрэглэ.'},
    {id:'g-wordform',type:'grammar',title:'Word Formation',subtitle:'noun • verb • adjective • adverb',level:'B1–B2',exam:'High',mn:'Өгүүлбэр дотор шаардлагатай үгийн аймгийг тодорхойлоод suffix/prefix ашиглан зөв хэлбэр сонгоно.',formula:['-tion/-ment = noun','-ful/-less/-ive = adjective','-ly = adverb','un-/im-/dis- = negative prefix'],examples:['success → successful → successfully','possible → impossible'],tip:'Blank-ийн өмнө/дараах үгсээр ямар part of speech хэрэгтэйг эхлээд тогтоо.',mistake:'-ly төгсгөлтэй бүх үг adverb биш: friendly, lovely.'},

    {id:'v-health',type:'vocabulary',title:'Health & Medicine',subtitle:'эрүүл мэнд • өвчин • эмчилгээ',level:'A2–B2',exam:'Core',mn:'Эрүүл мэндийн сэдвийг дан ганц үг цээжлэхгүй. Үг + phrasal verb + collocation + pattern + word family гэсэн багцаар сурвал reading, gap-fill, word formation дээр илүү сайн танина.',words:[['symptom','шинж тэмдэг'],['treatment','эмчилгээ'],['recover','эдгэрэх'],['prescription','эмчийн жор'],['injury','гэмтэл'],['infection','халдвар'],['surgery','мэс засал'],['remedy','эмчилгээний арга'],['rash','тууралт'],['dose','тун']],phrasal:[['come down with','өвдөж эхлэх'],['get over','өвчнөөс эдгэрэх'],['pass out','ухаан алдах'],['pull through','хүнд өвчнийг даван туулах'],['wear off','нөлөө нь гарах']],collocations:[['make an appointment','цаг авах'],['take medicine','эм уух'],['in good health','эрүүл байх'],['suffer from','...-аар өвдөх'],['recover from','...-аас эдгэрэх']],patterns:[['be addicted to + noun/V-ing','...-д донтсон байх'],['benefit from + noun/V-ing','...-аас ашиг хүртэх'],['complain of/about','...-ыг зовиурлах/гомдоллох'],['be worried about','...-д санаа зовох'],['be likely to + V1','... магадлалтай']],wordforms:[['fit → fitness','чийрэг → чийрэг байдал'],['ill → illness','өвчтэй → өвчин'],['injure → injury','гэмтээх → гэмтэл'],['recover → recovery','эдгэрэх → эдгэрэлт'],['strong → strength → strengthen','хүчтэй → хүч → хүчирхэгжүүлэх']],tip:'Шинэ үгийг бүтэн холбоо үгээр нь сур: make an appointment, suffer from, recover from.'},
    {id:'v-environment',type:'vocabulary',title:'Environment & Nature',subtitle:'байгаль • уур амьсгал • хамгаалал',level:'A2–B2',exam:'Core',mn:'Environment сэдэвт үгийг үйл үгтэй нь холбоод сур. Ингэснээр reading-ийн paraphrase болон word choice дээр хурдан танина.',words:[['pollution','бохирдол'],['climate change','уур амьсгалын өөрчлөлт'],['renewable energy','сэргээгдэх эрчим хүч'],['conservation','хамгаалал'],['habitat','амьдрах орчин'],['endangered','устах аюултай'],['deforestation','ойн хомсдол'],['drought','ган'],['ecosystem','экосистем'],['emission','ялгаруулалт']],phrasal:[['cut down','бууруулах/мод огтлох'],['die out','мөхөх'],['throw away','хаях'],['clean up','цэвэрлэх'],['use up','дуусгаж хэрэглэх']],collocations:[['protect the environment','байгаль орчноо хамгаалах'],['reduce waste','хог хаягдлыг бууруулах'],['save energy','эрчим хүч хэмнэх'],['natural resources','байгалийн нөөц'],['global warming','дэлхийн дулаарал']],patterns:[['protect ... from','...-аас хамгаалах'],['be responsible for','...-ыг хариуцах/шалтгаан болох'],['result in','...-д хүргэх'],['lead to','...-д хүргэх'],['contribute to','...-д хувь нэмэр оруулах']],wordforms:[['pollute → pollution → polluted','бохирдуулах → бохирдол → бохирдсон'],['protect → protection → protective','хамгаалах → хамгаалалт → хамгаалах зориулалттай'],['environment → environmental','байгаль орчин → байгаль орчны'],['conserve → conservation','хамгаалах → хамгаалал'],['destroy → destruction → destructive','устгах → сүйрэл → сүйтгэгч']],tip:'Environment reading дээр cause–effect хэллэгүүдийг хамтад нь ажигла.'},
    {id:'v-personality',type:'vocabulary',title:'Personality & Character',subtitle:'зан чанар • хүмүүсийг дүрслэх',level:'A2–B1',exam:'Core',mn:'Personality adjective-ийг дангаар нь биш, ямар preposition болон noun-тэй хэрэглэдгийг хамтад нь сур.',words:[['reliable','найдвартай'],['generous','өгөөмөр'],['patient','тэвчээртэй'],['stubborn','зөрүүд'],['sociable','нийтэч'],['confident','өөртөө итгэлтэй'],['sensitive','эмзэг'],['ambitious','амбици ихтэй'],['honest','шударга'],['selfish','хувиа хичээсэн']],phrasal:[['get along with','эвтэй байх'],['look up to','хүндэтгэх'],['stand up for','өмгөөлөх'],['calm down','тайвшрах'],['open up','сэтгэлээ нээх']],collocations:[['strong personality','хүчтэй зан чанар'],['sense of humour','хошин шогийн мэдрэмж'],['make friends','найзтай болох'],['keep a promise','амласнаа биелүүлэх'],['lose patience','тэвчээр алдах']],patterns:[['kind to','...-д эелдэг'],['patient with','...-д тэвчээртэй'],['proud of','...-аар бахархах'],['good at','...-д сайн'],['interested in','...-д сонирхолтой']],wordforms:[['honest → honesty','шударга → шударга зан'],['patient → patience','тэвчээртэй → тэвчээр'],['confident → confidence','өөртөө итгэлтэй → итгэл'],['generous → generosity','өгөөмөр → өгөөмөр зан'],['responsible → responsibility','хариуцлагатай → хариуцлага']],tip:'Adjective + preposition хосыг бүхэлд нь тогтоо.'},
    {id:'v-money',type:'vocabulary',title:'Money & Banking',subtitle:'мөнгө • банк • санхүү',level:'B1–B2',exam:'Core',mn:'Money topic дээр borrow/lend, spend/save зэрэг эсрэг утгатай үгсийг context-оор ялгаж сур.',words:[['income','орлого'],['expense','зардал'],['budget','төсөв'],['afford','төлөх чадвартай байх'],['borrow','зээлж авах'],['lend','зээлдүүлэх'],['interest rate','хүүгийн түвшин'],['debt','өр'],['transaction','гүйлгээ'],['salary','цалин']],phrasal:[['pay back','өрөө буцааж төлөх'],['save up','мөнгө хуримтлуулах'],['cut back on','зарцуулалтаа багасгах'],['run out of','дуусах'],['pay for','...-ын төлбөр төлөх']],collocations:[['earn money','мөнгө олох'],['save money','мөнгө хадгалах'],['spend money on','...-д мөнгө зарцуулах'],['take out a loan','зээл авах'],['bank account','банкны данс']],patterns:[['borrow ... from','...-аас зээлж авах'],['lend ... to','...-д зээлдүүлэх'],['spend ... on','...-д зарцуулах'],['pay for','...-ын төлөө төлөх'],['afford to + V1','... хийх мөнгөний боломжтой']],wordforms:[['economy → economic → economical','эдийн засаг → эдийн засгийн → хэмнэлттэй'],['finance → financial','санхүү → санхүүгийн'],['invest → investment → investor','хөрөнгө оруулах → хөрөнгө оруулалт → хөрөнгө оруулагч'],['employ → employment → employer/employee','ажиллуулах → ажил эрхлэлт → ажил олгогч/ажилтан'],['value → valuable','үнэ цэнэ → үнэ цэнтэй']],tip:'borrow = авах, lend = өгөх гэдгийг чиглэлээр нь бод.'},
    {id:'v-education',type:'vocabulary',title:'Education & Learning',subtitle:'сургууль • суралцах • шалгалт',level:'A2–B2',exam:'Core',mn:'Education vocabulary-г шалгалтын бодит үйлдэлтэй нь холбож сур: take an exam, meet a deadline, hand in an assignment.',words:[['assignment','даалгавар'],['curriculum','сургалтын хөтөлбөр'],['assessment','үнэлгээ'],['achievement','амжилт'],['qualification','мэргэшлийн үнэмлэх/зэрэг'],['graduate','төгсөх'],['revise','давтах'],['deadline','эцсийн хугацаа'],['scholarship','тэтгэлэг'],['compulsory','заавал']],phrasal:[['hand in','даалгавар хураалгах'],['catch up','хоцрогдлоо нөхөх'],['fall behind','хоцрох'],['look up','лавлах'],['drop out','сургуулиас гарах']],collocations:[['take an exam','шалгалт өгөх'],['pass/fail an exam','шалгалтад тэнцэх/унах'],['meet a deadline','хугацаандаа амжих'],['get a degree','зэрэг авах'],['make progress','ахиц гаргах']],patterns:[['prepare for','...-д бэлдэх'],['succeed in + V-ing','... хийхэд амжилт гаргах'],['be good at','...-д сайн'],['focus on','...-д төвлөрөх'],['apply for','...-д өргөдөл гаргах']],wordforms:[['educate → education → educational','боловсруулах → боловсрол → боловсролын'],['achieve → achievement','амжилтад хүрэх → амжилт'],['qualify → qualification','шаардлага хангах → мэргэшил'],['compete → competition → competitive','өрсөлдөх → өрсөлдөөн → өрсөлдөөнтэй'],['graduate → graduation','төгсөх → төгсөлт']],tip:'Exam vocabulary дээр verb + noun collocation-оо цээжил.'},
    {id:'v-technology',type:'vocabulary',title:'Technology & Digital Life',subtitle:'технологи • интернет • цахим хэрэглээ',level:'A2–B2',exam:'Core',mn:'Technology сэдэвт үгсийг өдөр тутмын digital action-тай холбож сураарай.',words:[['device','төхөөрөмж'],['privacy','нууцлал'],['software','программ хангамж'],['update','шинэчлэлт'],['access','хандах эрх'],['upload','байршуулах'],['download','татах'],['data breach','өгөгдөл алдагдах'],['artificial intelligence','хиймэл оюун ухаан'],['digital literacy','дижитал боловсрол']],phrasal:[['log in','нэвтрэх'],['sign up','бүртгүүлэх'],['scroll down','доош гүйлгэх'],['back up','нөөцлөх'],['shut down','унтраах']],collocations:[['protect your privacy','нууцлалаа хамгаалах'],['install software','программ суулгах'],['create an account','бүртгэл үүсгэх'],['strong password','хүчтэй нууц үг'],['internet connection','интернет холболт']],patterns:[['have access to','...-д хандах эрхтэй'],['connect to','...-д холбогдох'],['depend on','...-оос хамаарах'],['protect ... from','...-аас хамгаалах'],['be responsible for','...-ыг хариуцах']],wordforms:[['technology → technological','технологи → технологийн'],['digit → digital → digitally','тоо/цифр → дижитал → дижиталаар'],['connect → connection','холбох → холболт'],['secure → security','аюулгүй → аюулгүй байдал'],['inform → information','мэдээлэх → мэдээлэл']],tip:'Digital verb-үүдийг бодит үйлдлээр төсөөл: log in, back up, upload.'},
    {id:'v-crime',type:'vocabulary',title:'Crime & Law',subtitle:'гэмт хэрэг • хууль • шийтгэл',level:'B1–B2',exam:'Core',mn:'Crime & Law дээр action, person, place гэсэн гурван өнцгөөр үгээ холбож сур.',words:[['crime','гэмт хэрэг'],['criminal','гэмт хэрэгтэн'],['victim','хохирогч'],['evidence','нотлох баримт'],['arrest','баривчлах'],['court','шүүх'],['sentence','ял оноох/ял'],['guilty','буруутай'],['innocent','гэм буруугүй'],['fine','торгууль']],phrasal:[['break into','хүчээр нэвтрэх'],['get away','зугтах'],['give oneself up','өөрийгөө баривчлуулах'],['look into','шалган мөрдөх'],['carry out','гүйцэтгэх']],collocations:[['commit a crime','гэмт хэрэг үйлдэх'],['break the law','хууль зөрчих'],['find someone guilty','буруутай гэж тогтоох'],['serve a sentence','ял эдлэх'],['report a crime','гэмт хэрэг мэдээлэх']],patterns:[['accuse ... of','...-ыг ...-д буруутгах'],['charge ... with','...-ыг ... хэргээр яллах'],['blame ... for','...-д буруутгах'],['be guilty of','...-д буруутай'],['be responsible for','...-ыг хариуцах']],wordforms:[['crime → criminal','гэмт хэрэг → гэмт хэрэгтэн/гэмт'],['steal → theft → thief','хулгайлах → хулгай → хулгайч'],['rob → robbery → robber','дээрэмдэх → дээрэм → дээрэмчин'],['law → legal → illegal','хууль → хууль ёсны → хууль бус'],['punish → punishment','шийтгэх → шийтгэл']],tip:'steal vs rob: steal + thing, rob + person/place.'},
    {id:'v-travel',type:'vocabulary',title:'Travel & Transport',subtitle:'аялал • тээвэр • нислэг',level:'A2–B1',exam:'Core',mn:'Travel vocabulary-г аяллын дарааллаар төсөөл: book → depart → travel → arrive → stay.',words:[['destination','очих газар'],['departure','хөдлөх/нисэх'],['arrival','ирэх'],['delay','саатал'],['luggage','ачаа тээш'],['accommodation','байрлах газар'],['journey','аялал/зам'],['fare','унааны үнэ'],['board','тээврийн хэрэгсэлд суух'],['cancel','цуцлах']],phrasal:[['set off','замд гарах'],['check in','бүртгүүлэх'],['get on','унаанд суух'],['get off','унаанаас буух'],['pick up','тосож авах']],collocations:[['book accommodation','байр захиалах'],['catch a bus','автобусанд амжих'],['miss a flight','нислэгээс хоцрох'],['boarding pass','суух тасалбар'],['travel abroad','гадаадад аялах']],patterns:[['arrive in','хот/улсад ирэх'],['arrive at','жижиг газар/байршилд ирэх'],['travel by','...-аар аялах'],['go on a trip','аялалд явах'],['be delayed by','...-аас болж саатах']],wordforms:[['travel → traveller','аялах → аялагч'],['tour → tourist → tourism','аялал → жуулчин → аялал жуулчлал'],['arrive → arrival','ирэх → ирэлт'],['depart → departure','хөдлөх → хөдлөлт'],['fly → flight','нисэх → нислэг']],tip:'arrive in + city/country, arrive at + smaller place гэдгийг ялга.'},
    {id:'v-work',type:'vocabulary',title:'Work & Careers',subtitle:'ажил • мэргэжил • карьер',level:'B1–B2',exam:'Core',mn:'Work topic дээр job, career, employer, employee зэрэг үгсийг зөв ялгаж, ажлын үйл явцтай холбоод сур.',words:[['career','карьер'],['occupation','ажил мэргэжил'],['vacancy','сул орон тоо'],['employer','ажил олгогч'],['employee','ажилтан'],['salary','цалин'],['promotion','албан тушаал дэвших'],['experience','туршлага'],['skill','ур чадвар'],['retire','тэтгэвэрт гарах']],phrasal:[['take on','ажилтан авах/хариуцлага авах'],['carry out','гүйцэтгэх'],['set up','байгуулах'],['take over','удирдлагыг авах'],['step down','албан тушаалаас буух']],collocations:[['apply for a job','ажилд орох хүсэлт гаргах'],['gain experience','туршлага хуримтлуулах'],['earn a salary','цалин авах'],['work overtime','илүү цагаар ажиллах'],['job interview','ажлын ярилцлага']],patterns:[['apply for','...-д өргөдөл гаргах'],['work as','...-аар ажиллах'],['work for','... байгууллагад ажиллах'],['be responsible for','...-ыг хариуцах'],['have experience in','...-д туршлагатай']],wordforms:[['employ → employer/employee → employment','ажиллуулах → ажил олгогч/ажилтан → ажил эрхлэлт'],['apply → application → applicant','өргөдөл гаргах → өргөдөл → өргөдөл гаргагч'],['promote → promotion','дэвшүүлэх → дэвшил'],['retire → retirement','тэтгэвэрт гарах → тэтгэвэр'],['manage → manager → management','удирдах → менежер → удирдлага']],tip:'job = тодорхой ажил, career = урт хугацааны мэргэжлийн зам.'},
    {id:'v-relationships',type:'vocabulary',title:'Relationships & Society',subtitle:'харилцаа • гэр бүл • нийгэм',level:'A2–B2',exam:'Core',mn:'Relationships topic дээр хүмүүсийн хоорондын үйлдэл, зан төлөв, холбоог илэрхийлэх хэллэгүүдийг хамтад нь сур.',words:[['relationship','харилцаа'],['relative','хамаатан'],['neighbour','хөрш'],['community','нийгэмлэг'],['support','дэмжлэг'],['trust','итгэл'],['respect','хүндлэл'],['argument','маргаан'],['generation','үе'],['volunteer','сайн дурын ажилтан']],phrasal:[['get on with','эвтэй байх'],['fall out with','муудалцах'],['make up','эвлэрэх'],['grow up','өсөж томрох'],['look after','асрах']],collocations:[['close friend','дотны найз'],['keep in touch','холбоотой байх'],['have an argument','маргалдах'],['show respect','хүндлэл үзүүлэх'],['support each other','бие биенээ дэмжих']],patterns:[['get on with','...-тай эвтэй байх'],['be close to','...-тай дотно байх'],['argue with ... about','...-тай ... талаар маргах'],['depend on','...-оос хамаарах'],['care about','...-д санаа тавих']],wordforms:[['relate → relation/relationship → relative','холбогдох → холбоо/харилцаа → хамаатан'],['support → supportive','дэмжих → дэмждэг'],['respect → respectful','хүндлэх → хүндэтгэлтэй'],['society → social','нийгэм → нийгмийн'],['communicate → communication','харилцах → харилцаа']],tip:'Relationship vocabulary-г verb + preposition хэлбэрээр сайн тогтоо.'},

    {id:'p-get',type:'phrasal',title:'GET phrasal verbs',subtitle:'get up • get along • get over...',level:'A2–B2',exam:'High',mn:'GET-тэй phrasal verb-үүд маш олон утгатай тул context-оор ялгана.',words:[['get up','босох'],['get along with','эвтэй байх'],['get over','даван туулах/эдгэрэх'],['get back','буцаж ирэх'],['get rid of','салах/зайлуулах'],['get through','даван гарах/холбогдох']],tip:'Phrasal verb-ийг дан ганц verb-ээр биш бүтэн хэллэгээр нь цээжил.'},
    {id:'p-take',type:'phrasal',title:'TAKE phrasal verbs',subtitle:'take off • take after • take up...',level:'A2–B2',exam:'High',mn:'TAKE-тэй phrasal verb-ийн утга particle-ээс хамаарч эрс өөрчлөгдөнө.',words:[['take off','хөөрөх/тайлах'],['take after','адилхан байх'],['take up','эхлэх/зай эзлэх'],['take over','удирдлагыг авах'],['take back','буцааж авах/үгээ буцаах'],['take care of','асрах/хариуцах']],tip:'take up a hobby = шинэ хобби эхлэх.'},
    {id:'p-look',type:'phrasal',title:'LOOK phrasal verbs',subtitle:'look after • look for • look forward to',level:'A2–B2',exam:'High',mn:'LOOK-тэй холбоо үгс reading болон gap-fill-д түгээмэл.',words:[['look after','асрах'],['look for','хайх'],['look up','лавлаж харах'],['look into','судлах'],['look out','болгоомжлох'],['look forward to','тэсэн ядан хүлээх']],tip:'look forward to + noun/V-ing.'},
    {id:'p-put',type:'phrasal',title:'PUT phrasal verbs',subtitle:'put off • put on • put up with',level:'B1–B2',exam:'High',mn:'PUT-тэй phrasal verb-үүд delay, wear, tolerate зэрэг утгыг илэрхийлнэ.',words:[['put off','хойшлуулах'],['put on','өмсөх/асаах'],['put out','унтраах'],['put away','хураах'],['put up with','тэвчих'],['put together','угсрах/нэгтгэх']],tip:'put off + noun/V-ing.'},
    {id:'p-turn',type:'phrasal',title:'TURN phrasal verbs',subtitle:'turn on • turn down • turn out',level:'A2–B2',exam:'High',mn:'TURN particle-тэйгээ нийлээд асаах, татгалзах, үр дүнд хүрэх гэх мэт утга гаргана.',words:[['turn on','асаах'],['turn off','унтраах'],['turn down','татгалзах/намсгах'],['turn up','гарч ирэх/чангаруулах'],['turn out','эцэстээ ... болох'],['turn into','... болж хувирах']],tip:'turn down an offer = саналаас татгалзах.'},
    {id:'p-break',type:'phrasal',title:'BREAK phrasal verbs',subtitle:'break down • break out • break up',level:'B1–B2',exam:'Medium',mn:'BREAK-тэй phrasal verb нь эвдрэх, дэгдэх, салгах зэрэг утгатай.',words:[['break down','эвдрэх'],['break out','гэнэт эхлэх/дэгдэх'],['break up','салах/тараах'],['break into','хүчээр нэвтрэх'],['break off','таслах'],['break through','саадыг нэвтрэх']],tip:'The car broke down = машин эвдэрсэн.'},

    {id:'i-piececake',type:'idiom',title:'a piece of cake',subtitle:'маш амархан зүйл',level:'A2–B1',exam:'Common',mn:'Хийхэд маш амархан, төвөггүй зүйл.',examples:['The test was a piece of cake. — Шалгалт маш амархан байсан.'],tip:'Literal утгаар “бялууны нэг хэсэг” боловч idiom утга нь “маш амархан”.'},
    {id:'i-breakice',type:'idiom',title:'break the ice',subtitle:'эвгүй байдлыг арилгах',level:'B1',exam:'Common',mn:'Танихгүй хүмүүсийн хоорондын эхний эвгүй, дуугүй байдлыг арилгах.',examples:['The teacher told a joke to break the ice.'],tip:'Conversation/social situation-д хэрэглэнэ.'},
    {id:'i-hitbooks',type:'idiom',title:'hit the books',subtitle:'шаргуу хичээллэх',level:'B1',exam:'Common',mn:'Шалгалт зэрэгт бэлдэхийн тулд эрчимтэй хичээллэж эхлэх.',examples:['I have an exam tomorrow, so I need to hit the books.'],tip:'Education context-д informal хэллэг.'},
    {id:'i-underweather',type:'idiom',title:'under the weather',subtitle:'бие тавгүй байх',level:'B1',exam:'Common',mn:'Бага зэрэг өвдсөн, бие тавгүй байгаа байдлыг хэлнэ.',examples:['I’m feeling under the weather today.'],tip:'Health сэдэвт informal expression.'},
    {id:'i-costarm',type:'idiom',title:'cost an arm and a leg',subtitle:'маш үнэтэй',level:'B1',exam:'Common',mn:'Үнэ нь хэт өндөр, маш их мөнгө шаардсан зүйл.',examples:['That new phone costs an arm and a leg.'],tip:'Money/shopping context-д түгээмэл.'},
    {id:'i-onceblue',type:'idiom',title:'once in a blue moon',subtitle:'маш ховор',level:'B1',exam:'Common',mn:'Маш ховор тохиолддог үйл явдлыг хэлнэ.',examples:['We eat out once in a blue moon.'],tip:'Frequency expression-ийн оронд хэрэглэж болно.'},
    {id:'i-bitebullet',type:'idiom',title:'bite the bullet',subtitle:'хэцүү зүйлийг зориглон хийх',level:'B2',exam:'Useful',mn:'Тааламжгүй боловч зайлшгүй хийх ёстой зүйлээ зориглон хийх.',examples:['I decided to bite the bullet and speak to my manager.'],tip:'Decision/problem context.'},
    {id:'i-ontopworld',type:'idiom',title:'on top of the world',subtitle:'маш их баяртай',level:'B1',exam:'Useful',mn:'Маш аз жаргалтай, баяр хөөртэй байх.',examples:['She felt on top of the world after passing the exam.'],tip:'Emotion/personality context.'}
  ];
  const $=id=>document.getElementById(id);
  let type='grammar', search='';
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function badge(t){return t==='grammar'?'📘 Grammar':t==='vocabulary'?'📗 Vocabulary':t==='phrasal'?'🔗 Phrasal Verb':'💬 Idiom'}
  function render(){
    const grid=$('learningGridV59'); if(!grid)return;
    const q=search.trim().toLowerCase();
    const a=lessons.filter(x=>x.type===type && (!q || JSON.stringify(x).toLowerCase().includes(q)));
    $('learningCountV59').textContent=a.length;
    $('learningEmptyV59')?.classList.toggle('hidden',a.length>0);
    grid.innerHTML=a.map(x=>`<article class="learning-card-v59" data-lesson-id="${x.id}"><div class="learning-card-top-v59"><span>${badge(x.type)}</span><span class="learning-level-v59">${esc(x.level)}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.subtitle||'')}</p><div class="learning-meta-v59"><span>🎯 ${esc(x.exam||'Exam')}</span><span>🇲🇳 тайлбартай</span></div><button class="primary-btn small" data-open-lesson="${x.id}">Хичээл үзэх</button></article>`).join('');
    grid.querySelectorAll('[data-open-lesson]').forEach(b=>b.onclick=()=>openLesson(b.dataset.openLesson));
  }
  function rows(words){return `<div class="lesson-word-list-v59">${(words||[]).map(w=>`<div><b>${esc(w[0])}</b><span>${esc(w[1])}</span></div>`).join('')}</div>`}
  function openLesson(id){
    const x=lessons.find(v=>v.id===id); if(!x)return;
    let body=`<div class="lesson-breadcrumb-v59">${badge(x.type)} • ${esc(x.level)} • Exam: ${esc(x.exam||'')}</div><h2>${esc(x.title)}</h2><p class="lesson-sub-v59">${esc(x.subtitle||'')}</p><div class="lesson-mn-v59"><b>🇲🇳 Монгол тайлбар</b><p>${esc(x.mn||'')}</p></div>`;
    if(x.formula) body+=`<h3>🧩 Бүтэц</h3><ul class="lesson-list-v59">${x.formula.map(v=>`<li><code>${esc(v)}</code></li>`).join('')}</ul>`;
    if(x.words) body+=`<h3>📘 Topic Vocabulary</h3>${rows(x.words)}`;
    if(x.phrasal) body+=`<h3>🔗 Phrasal Verbs</h3>${rows(x.phrasal)}`;
    if(x.collocations) body+=`<h3>🧩 Phrases & Collocations</h3>${rows(x.collocations)}`;
    if(x.patterns) body+=`<h3>🧠 Word Patterns</h3>${rows(x.patterns)}`;
    if(x.wordforms) body+=`<h3>🌱 Word Formation</h3>${rows(x.wordforms)}`;
    if(x.examples) body+=`<h3>✏️ Жишээ</h3><ul class="lesson-list-v59">${x.examples.map(v=>`<li>${esc(v)}</li>`).join('')}</ul>`;
    if(x.tip) body+=`<div class="lesson-tip-v59"><b>🎯 ЭЕШ Tip</b><p>${esc(x.tip)}</p></div>`;
    if(x.mistake) body+=`<div class="lesson-warning-v59"><b>⚠️ Түгээмэл алдаа</b><p>${esc(x.mistake)}</p></div>`;
    body+=`<div class="lesson-actions-v59"><button class="primary-btn" id="lessonPracticeV59">Practice хийх</button><button class="secondary-btn" id="lessonDoneV59">✓ Үзсэн гэж тэмдэглэх</button></div>`;
    $('learningModalBodyV59').innerHTML=body; $('learningModalV59').classList.remove('hidden');
    $('lessonPracticeV59').onclick=()=>{try{localStorage.setItem('smarteshV59PracticeTopic',x.title)}catch(e){};$('learningModalV59').classList.add('hidden'); if(window.showView)window.showView('practiceHub'); else document.querySelector('[data-view="practiceHub"]')?.click();};
    $('lessonDoneV59').onclick=()=>{let a=[];try{a=JSON.parse(localStorage.getItem('smarteshLearningDoneV59')||'[]')}catch(e){}; if(!a.includes(id))a.push(id);localStorage.setItem('smarteshLearningDoneV59',JSON.stringify(a));$('lessonDoneV59').textContent='✓ Үзсэн';};
  }
  $('learningTabsV59')?.querySelectorAll('[data-learn-type]').forEach(b=>b.onclick=()=>{type=b.dataset.learnType;$('learningTabsV59').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));render();});
  $('learningSearchV59')?.addEventListener('input',e=>{search=e.target.value;render()});
  $('learningCloseV59')?.addEventListener('click',()=> $('learningModalV59').classList.add('hidden'));
  $('learningModalV59')?.addEventListener('click',e=>{if(e.target.id==='learningModalV59')e.currentTarget.classList.add('hidden')});
  const searchEl=$('learningSearchV59');
  if(searchEl) search=searchEl.value||'';
  window.SmartESH_LearningV59={lessons,openLesson,render};
  render();
})();
