// SmartESH v61 — Humanized EESH Learning Center + Free/Premium gating
(function(){
const lessons=[
{id:'g1',type:'grammar',title:'Present Simple',sub:'Дадал, тогтмол үйлдэл, баримт',free:true,sections:[['Гол санаа','Өдөр бүр, байнга давтагддаг зүйл болон өөрчлөгддөггүй баримтыг хэлэхэд хэрэглэнэ. “Одоо яг юу хийж байна?” биш, “ер нь юу хийдэг вэ?” гэж бодоорой.'],['Бүтэц','I/You/We/They + V1. He/She/It + V-s/es. Negative: do/does not + V1. Question: Do/Does + subject + V1?'],['Жишээ','She studies English every evening. — Тэр орой бүр англи хэл үздэг.\nHe doesn’t watch TV before school.\nDoes your brother play basketball?'],['ЭЕШ-ийн урхи','does/doesn’t орсон үед үндсэн үйл үг V1 болно: “Does she likes?” ❌ → “Does she like?” ✅'],['Санах арга','usually, often, always, sometimes, never, every day/week зэрэг нь хүчтэй дохио боловч зөвхөн signal word биш өгүүлбэрийн утгыг шалга.']]},
{id:'g2',type:'grammar',title:'Present Continuous',sub:'Одоо болж буй болон түр зуурын үйлдэл',free:true,sections:[['Гол санаа','Яг одоо болж байгаа эсвэл энэ үеэр түр хугацаанд үргэлжилж буй үйлдлийг хэлнэ.'],['Бүтэц','am/is/are + V-ing. Negative: am/is/are not + V-ing. Question: Am/Is/Are + subject + V-ing?'],['Жишээ','Look! It is snowing.\nI’m staying with my aunt this week. — Энэ долоо хоногт нагацындаа түр байгаа.'],['Хоёрыг бүү андуур','I work at a school. = байнгын ажил. I am working from home this week. = түр зуурын байдал.'],['ЭЕШ-ийн урхи','know, believe, understand, want зэрэг state verb-ийг ерөнхийдөө continuous-д хэрэглэхгүй: I am knowing ❌.']]},
{id:'g3',type:'grammar',title:'Present Perfect',sub:'Өнгөрсөн үйл явдал + одоогийн холбоо',sections:[['Гол санаа','Яг хэдийд болсныг биш, одоотой ямар холбоотойг нь онцолдог. Туршлага, одоогийн үр дүн, одоо хүртэл үргэлжилсэн хугацаанд түгээмэл.'],['Бүтэц','have/has + V3'],['Жишээ','I have lost my key. → Одоо түлхүүр надад алга.\nShe has visited Korea twice.\nWe have lived here for five years.'],['Present Perfect vs Past Simple','I have been to Korea. = амьдралын туршлага. I went to Korea in 2024. = тодорхой дууссан өнгөрсөн хугацаа.'],['ЭЕШ-ийн урхи','yesterday, last year, in 2024 зэрэг дууссан хугацаатай Present Perfect бүү хэрэглэ. since = эхлэх цэг; for = хугацаа.']]},
{id:'g4',type:'grammar',title:'Present Perfect Continuous',sub:'Өнгөрсөнд эхэлсэн, үргэлжилж буй үйлдэл',sections:[['Гол санаа','Үйлдлийн үргэлжилсэн хугацаа, явцыг онцолно.'],['Бүтэц','have/has been + V-ing'],['Жишээ','She has been studying for three hours.'],['Compare','I have read the book. → үр дүн/дууссан байж болно. I have been reading the book. → явц, хугацаа онцолно.'],['Анхаар','State verb-үүдтэй perfect simple илүү түгээмэл: I have known her for years.']]},
{id:'g5',type:'grammar',title:'Past Simple',sub:'Дууссан өнгөрсөн үйлдэл',sections:[['Гол санаа','Өнгөрсөнд тодорхой үед болсон, дууссан үйлдэл.'],['Бүтэц','V2; did not + V1; Did + S + V1?'],['Жишээ','We visited Kharkhorin last summer.'],['ЭЕШ-ийн урхи','did-ийн дараа V2 биш V1: Did you went? ❌ → Did you go? ✅']]},
{id:'g6',type:'grammar',title:'Past Continuous',sub:'Өнгөрсөн мөчид үргэлжилж байсан үйлдэл',sections:[['Гол санаа','Нэг үйл явдал болж байхад өөр үйл явдал тасалдуулсан нөхцөлд их орно.'],['Бүтэц','was/were + V-ing'],['Жишээ','I was studying when my friend called.'],['Compare','Long background action → Past Continuous; interrupting short action → Past Simple.']]},
{id:'g7',type:'grammar',title:'Past Perfect',sub:'Өнгөрсөн дэх “өмнөх” үйлдэл',sections:[['Гол санаа','Өнгөрсөн хоёр үйл явдлын аль нь түрүүлж болсныг тодруулна.'],['Бүтэц','had + V3'],['Жишээ','The train had left before we arrived.'],['Санах арга','Өнгөрсөн timeline зур. Түрүүлсэн үйлдэл → Past Perfect; дараагийнх → Past Simple.']]},
{id:'g8',type:'grammar',title:'Future Forms',sub:'will • be going to • present continuous',sections:[['Гол санаа','Future гэдэг нэг л цаг биш. Шууд шийдвэр/таамагт will, нотолгоотой таамаг/урьдчилсан зорилгод going to, товлосон хувийн төлөвлөгөөнд Present Continuous.'],['Жишээ','I’ll answer the phone.\nLook at those clouds! It’s going to rain.\nI’m meeting my teacher at 4.'],['ЭЕШ-ийн урхи','Timetable: The train leaves at 7.30. → Present Simple future meaning.']]},
{id:'g9',type:'grammar',title:'Tense Comparison Lab',sub:'Present/Past/Perfect-ийг зэрэгцүүлж ялгах',sections:[['Алхам 1','Time line-аа ол: present уу, finished past уу, present connection уу?'],['Алхам 2','Action completed уу, process уу? Habit уу, temporary уу?'],['Compare','She works here. = байнгын.\nShe is working here this month. = түр.\nShe worked here in 2024. = дууссан.\nShe has worked here since 2024. = одоо хүртэл.'],['Шалгалтын арга','1) time expression, 2) meaning, 3) verb form гэсэн дарааллаар шалга.']]},
{id:'g10',type:'grammar',title:'Conditionals',sub:'Zero • First • Second • Third',sections:[['Гол санаа','Баримт → бодит боломж → төсөөлөл → өнгөрсөн харамсал гэсэн шатлалтай.'],['Бүтэц','Zero: if + present, present\nFirst: if + present, will + V1\nSecond: if + past, would + V1\nThird: if + had + V3, would have + V3'],['ЭЕШ-ийн урхи','First conditional-ийн if-clause дотор will ерөнхийдөө орохгүй.']]},
{id:'g11',type:'grammar',title:'Passive Voice',sub:'be + V3',sections:[['Гол санаа','Хэн хийсэн нь бус, юу болсон нь чухал үед passive.'],['Алхам','Object-ийг subject болго → tense-д тохирсон be → V3 → шаардлагатай бол by + agent.'],['Жишээ','People speak English worldwide. → English is spoken worldwide.']]},
{id:'g12',type:'grammar',title:'Reported Speech',sub:'said • told • asked',sections:[['Гол санаа','Хүний үгийг дамжуулахдаа pronoun, tense, time expression өөрчлөгдөж болно.'],['ЭЕШ-ийн урхи','Reported question statement word order-той: He asked where I lived.'],['Хоёрыг бүү андуур','say + clause; tell + person + clause.']]},
{id:'v1',type:'vocabulary',title:'Health & Medicine',sub:'symptoms • treatment • healthy habits',free:true,words:[['symptom','шинж тэмдэг','have/show symptoms'],['diagnose','оношлох','be diagnosed with'],['treatment','эмчилгээ','receive treatment'],['recover','эдгэрэх','recover from an illness'],['prevent','урьдчилан сэргийлэх','prevent disease'],['prescription','жор','get a prescription'],['balanced diet','тэнцвэртэй хооллолт','follow a balanced diet'],['immune system','дархлааны тогтолцоо','strengthen the immune system']],note:'Үгийг дангаар нь биш collocation-тай нь тогтоо. “diagnosed with”, “recover from” зэрэг preposition ЭЕШ-д сонголт болдог.'},
{id:'v2',type:'vocabulary',title:'Environment & Nature',sub:'climate • pollution • conservation',free:true,words:[['climate change','уур амьсгалын өөрчлөлт','combat climate change'],['pollution','бохирдол','reduce pollution'],['renewable energy','сэргээгдэх эрчим хүч','use renewable energy'],['habitat','амьдрах орчин','natural habitat'],['endangered','устах аюулд орсон','endangered species'],['conserve','хамгаалан хадгалах','conserve water'],['deforestation','ойн хомсдол','prevent deforestation'],['biodiversity','биологийн олон янз байдал','protect biodiversity']],note:'Reading-д үг яг давтагдахгүй, synonym/paraphrase хэлбэрээр ордог.'},
{id:'v3',type:'vocabulary',title:'Personality & Character',sub:'positive • negative • behaviour',words:[['reliable','найдвартай','a reliable person'],['generous','өгөөмөр','generous with time'],['stubborn','зөрүүд','too stubborn to change'],['considerate','бусдыг боддог','considerate towards others'],['confident','өөртөө итгэлтэй','feel confident about'],['sociable','нийтэч','a sociable student'],['ambitious','зорилготой','highly ambitious'],['sensitive','эмзэг/мэдрэмтгий','sensitive to criticism']],note:'Personality adjective-ийг behaviour adjective-тай андуурахгүй. Context-оор positive/negative connotation хар.'},
{id:'v4',type:'vocabulary',title:'Money & Banking',sub:'income • expenses • saving',words:[['income','орлого','monthly income'],['expense','зардал','living expenses'],['afford','худалдан авах чадвартай байх','can/can’t afford to'],['borrow','зээлж авах','borrow money from'],['lend','зээлдүүлэх','lend money to'],['save','хадгалах/хуримтлуулах','save up for'],['debt','өр','get into debt'],['budget','төсөв','stick to a budget']],note:'borrow FROM, lend TO — ЭЕШ-д түгээмэл андууруулдаг.'},
{id:'v5',type:'vocabulary',title:'Education & Learning',sub:'assessment • achievement • study',words:[['curriculum','сургалтын хөтөлбөр','school curriculum'],['assessment','үнэлгээ','continuous assessment'],['achievement','амжилт','academic achievement'],['revise','давтах','revise for an exam'],['assignment','даалгавар','submit an assignment'],['scholarship','тэтгэлэг','win a scholarship']],note:'exam/test-тэй do/take/sit/pass/fail гэсэн verbs-ийг collocation-аар сур.'},
{id:'v6',type:'vocabulary',title:'Technology & Media',sub:'digital life • privacy • AI',words:[['privacy','нууцлал','protect privacy'],['access','хандах эрх','have access to'],['device','төхөөрөмж','digital device'],['artificial intelligence','хиймэл оюун ухаан','AI-powered tool'],['misinformation','ташаа мэдээлэл','spread misinformation'],['cybersecurity','кибер аюулгүй байдал','improve cybersecurity']],note:'Technology reading-д cause/effect болон advantage/disadvantage үгсийг хамт анзаар.'},
{id:'c1',type:'communication',title:'Requests & Permission',sub:'Could you…? • Would you mind…? • May I…?',free:true,sections:[['Эхлээд function-ийг тань','“Would you mind opening the window?” бол мэдээлэл асуусан question биш — polite request.'],['Түгээмэл хэллэг','Could you help me, please?\nWould you mind waiting a moment?\nDo you mind if I sit here?\nMay I borrow your pen?'],['Зөв хариу','Sure. / Of course. / Not at all. / I’m afraid I can’t.'],['Урхи','Would you mind…? → “Not at all” нь зөвшөөрч байна гэсэн утгатай.']]},
{id:'c2',type:'communication',title:'Suggestions & Advice',sub:'Why don’t we…? • How about…? • You should…',free:true,sections:[['Ялгаа','Suggestion = хамт хийх санал. Advice = хүнд зөвлөгөө өгөх.'],['Хэллэг','Why don’t we go by bus?\nHow about meeting after class?\nYou’d better see a doctor.\nIf I were you, I’d talk to her.'],['Хариу','That’s a good idea. / Sounds great. / I’d rather not.'],['Арга','Асуултын keyword биш, speaker-ийн зорилгыг ол.']]},
{id:'c3',type:'communication',title:'Invitations & Offers',sub:'Would you like…? • Shall I…?',sections:[['Хэллэг','Would you like to join us?\nShall I carry that for you?\nCan I get you something to drink?'],['Хариу','I’d love to. / That would be great. / No, thanks. I’m fine.'],['Урхи','Would you like…? гэдэгт “Yes, I like” биш “Yes, I’d love to.”']]},
{id:'c4',type:'communication',title:'Apologies, Thanks & Sympathy',sub:'Sorry • Thank you • I’m sorry to hear that',sections:[['Apology','I’m terribly sorry. → That’s all right. / Don’t worry about it.'],['Thanks','Thanks a lot. → You’re welcome. / My pleasure.'],['Sympathy','I failed my exam. → I’m sorry to hear that.'],['Арга','Эхний speaker-ийн emotion/situation-ийг тодорхойлоод socially appropriate response сонго.']]},
{id:'c5',type:'communication',title:'Agreeing & Disagreeing',sub:'So do I • Neither do I • I don’t think so',sections:[['Хэллэг','I think… / In my opinion… / I totally agree. / I’m not sure I agree.'],['Grammar response','I love reading. → So do I.\nI can’t swim. → Neither can I.'],['Урхи','Auxiliary-г эх өгүүлбэртэй тааруул: So am I / So do I / So have I.']]},
{id:'c6',type:'communication',title:'Clarifying & Everyday Functions',sub:'Pardon? • What do you mean? • Could you repeat that?',sections:[['Түгээмэл','Sorry, I didn’t catch that.\nCould you say that again?\nWhat do you mean by…?\nLet me check I understood you correctly.'],['Exam method','1. Situation → 2. Function → 3. Tone → 4. Grammar fit → 5. Eliminate unnatural response.']]},
{id:'r1',type:'reading',title:'Reading Strategy: Main Idea & Detail',sub:'Skim → locate → prove',free:true,sections:[['Main idea','Гарчиг, эхний/сүүлийн өгүүлбэр, давтагдсан санааг хар. Нэг жижиг detail-ийг main idea гэж бүү сонго.'],['Detail question','Асуултын keyword-ийг passage-д яг адил үгээр хайх биш synonym/paraphrase хай.'],['3 алхам','1) Question унш. 2) Evidence байрлалыг ол. 3) Сонголтоо passage-ийн үгээр нотол. Өөрийн мэдлэгээр хариулахгүй.']]},
{id:'r2',type:'reading',title:'Reading Strategy: Inference & Vocabulary',sub:'What can be inferred? • word in context',free:true,sections:[['Inference','Текстэд шууд бичээгүй ч evidence-ээс логикоор гарч болох хамгийн бага дүгнэлтийг сонго. Хэт хүчтэй “always/never/all” сонголтоос болгоомжил.'],['Vocabulary in context','Үгийг өгүүлбэрээс салгаж орчуулахгүй. Өмнөх/дараах өгүүлбэр, contrast/cause clues-ийг ашигла.'],['Reference','it/they/this/which юу зааж байгааг олохдоо өмнөх боломжит noun-уудын number + meaning-ийг шалга.']]},
{id:'r3',type:'reading',title:'Worked Reading 1 — Healthy Sleep',sub:'5 асуултыг багштай хамт задлая',sections:[['Passage','Many teenagers sleep less than the recommended amount because of homework, entertainment and late-night phone use. Lack of sleep can affect concentration, mood and memory. Researchers suggest keeping a regular bedtime and avoiding bright screens shortly before sleep. Even small changes to evening routines may help students feel more alert in class.'],['Q1 Main idea','What is the passage mainly about? → Teen sleep problems and simple ways to improve sleep. Evidence: эхний 2 өгүүлбэр problem, дараагийн 2 solution.'],['Q2 Detail','What can lack of sleep affect? → concentration, mood and memory. Энэ бол direct detail; passage-аас evidence-ээ яг ол.'],['Q3 Cause','Why do many teenagers sleep less? → homework, entertainment and late-night phone use. “because of” шалтгааны дохио.'],['Q4 Vocabulary','alert in class ≈ awake and able to pay attention. “alert” гэдгийг “warning” гэж шууд орчуулбал context-д тохирохгүй.'],['Q5 Advice','Which action is recommended? → avoiding bright screens before sleep. Distractor: “use phones to relax” нь passage-д байхгүй.']]},
{id:'r4',type:'reading',title:'Worked Reading 2 — Urban Green Spaces',sub:'ЭЕШ түвшний inference + reference + purpose',sections:[['Passage','As cities expand, parks and other green spaces can easily be treated as optional. However, studies increasingly link access to greenery with lower stress, more physical activity and cooler neighbourhood temperatures. These benefits are not distributed equally: some communities have far fewer safe green areas than others. For city planners, the challenge is therefore not simply to create more parks, but to consider where they are built and who can reach them.'],['Q1 Purpose','Writer’s main purpose? → To explain benefits of urban green spaces and the need for fair access. “Parks are beautiful” бол хэт нарийн.'],['Q2 Reference','“These benefits” → lower stress, more physical activity, cooler temperatures. Pronoun/reference асуултад өмнөх noun phrase-үүдийг шалга.'],['Q3 Inference','We can infer that simply increasing the total number of parks may not solve inequality. Evidence: “not simply… but… where… and who can reach them.”'],['Q4 Vocabulary','distributed equally ≈ shared/provided fairly across communities. Context нь money distribution биш access-ийн тэгш байдал.'],['Q5 Detail','What challenge do planners face? → location and accessibility, not only quantity. Сонголтын нэг хэсэг зөв байсан ч бүтэн утга passage-тай таарах ёстой.']]},
{id:'p1',type:'phrasal',title:'GET Phrasal Verbs',sub:'get over • get along • get through',free:true,words:[['get over','даван туулах/эдгэрэх','get over an illness'],['get along with','эвтэй байх','get along with classmates'],['get through','даван гарах/холбогдох','get through a difficult time'],['get rid of','салах','get rid of waste']],note:'Particle солигдоход утга бүхэлдээ өөрчлөгдөнө. Бүтэн chunk-аар цээжил.'},
{id:'p2',type:'phrasal',title:'TAKE Phrasal Verbs',sub:'take up • take after • take over',free:true,words:[['take up','шинээр эхлэх','take up a hobby'],['take after','адилхан байх','take after your mother'],['take over','удирдлагыг авах','take over a company'],['take off','хөөрөх/тайлах','the plane took off']],note:'Context-аар literal эсвэл phrasal утгыг ялга.'},
{id:'p3',type:'phrasal',title:'LOOK Phrasal Verbs',sub:'look after • look into • look forward to',words:[['look after','асрах','look after a child'],['look into','судлах','look into a problem'],['look forward to','тэсэн ядан хүлээх','look forward to meeting you'],['look up','лавлах','look up a word']],note:'look forward to + V-ing. Энд to нь infinitive marker биш preposition.'},
{id:'p4',type:'phrasal',title:'PUT / TURN / BREAK',sub:'high-frequency exam set',words:[['put off','хойшлуулах','put off doing homework'],['put up with','тэвчих','put up with noise'],['turn down','татгалзах','turn down an offer'],['turn out','эцэстээ болох','turn out well'],['break down','эвдрэх','car broke down'],['break out','дэгдэх','a fire broke out']],note:'Gap-fill дээр particle бүрийн утгыг elimination-аар шалга.'},
{id:'i1',type:'idiom',title:'Everyday Idioms 1',sub:'piece of cake • break the ice • under the weather',free:true,words:[['a piece of cake','маш амархан','The quiz was a piece of cake.'],['break the ice','эхний эвгүй байдлыг арилгах','A game helped break the ice.'],['under the weather','бие тавгүй','I feel under the weather.']],note:'Idiom-ийг үг үгээр нь орчуулахгүй; situation-тай нь сур.'},
{id:'i2',type:'idiom',title:'Everyday Idioms 2',sub:'hit the books • once in a blue moon • on top of the world',free:true,words:[['hit the books','шаргуу хичээллэх','I need to hit the books.'],['once in a blue moon','маш ховор','We eat out once in a blue moon.'],['on top of the world','маш их баяртай','She felt on top of the world.']],note:'Dialogue question-д idiom-ийн tone болон context чухал.'},
{id:'i3',type:'idiom',title:'Money & Decision Idioms',sub:'cost an arm and a leg • bite the bullet',words:[['cost an arm and a leg','маш үнэтэй','The laptop cost an arm and a leg.'],['bite the bullet','хэцүү зүйлийг зориглон хийх','He bit the bullet and apologized.'],['make ends meet','орлого зарлагаа хүргэх','It is hard to make ends meet.']],note:'Literal зураглал нь утгыг таахад тусалж болно, гэхдээ context-оор баталгаажуул.'},
{id:'i4',type:'idiom',title:'Success & Challenge Idioms',sub:'get the hang of • go the extra mile',words:[['get the hang of','аргыг нь олох','I’m getting the hang of it.'],['go the extra mile','илүү чармайх','She always goes the extra mile.'],['learn the hard way','алдаанаасаа хүндээр сурах','He learned the hard way.']],note:'Meaning choice дээр хамгийн natural paraphrase-ийг сонго.'}
];
const types={grammar:'📘 Grammar',vocabulary:'📗 Vocabulary',communication:'💬 Communication',reading:'📖 Reading',phrasal:'🔗 Phrasal Verbs',idiom:'🗨️ Idioms'};
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let type='grammar',search='',premium=false,role='guest';
function me(){try{return typeof currentUser==='function'?currentUser():null}catch(e){return null}}
async function access(){const u=me();role=u?.role||'guest'; if(role==='admin'){premium=true;return render()} premium=(u?.access==='premium'||u?.access_status==='premium'); try{const sb=window.smarteshSupabase;if(sb&&u?.id){const {data}=await sb.from('entitlements').select('status,ends_at').eq('user_id',u.id).eq('status','active').order('ends_at',{ascending:false}).limit(1);if(data?.[0]&&new Date(data[0].ends_at)>new Date())premium=true}}catch(e){} render()}
function locked(x){return !x.free&&!premium&&role!=='admin'}
function render(){const grid=$('learningGridV59');if(!grid)return;const q=search.trim().toLowerCase();const a=lessons.filter(x=>x.type===type&&(!q||JSON.stringify(x).toLowerCase().includes(q)));$('learningCountV59').textContent=a.length;$('learningEmptyV59')?.classList.toggle('hidden',a.length>0);grid.innerHTML=a.map(x=>{const lock=locked(x);return `<article class="learning-card-v59 ${lock?'lesson-locked-v61':''}"><div class="learning-card-top-v59"><span>${types[x.type]}</span><span class="learning-level-v59">${x.free?'FREE':'PREMIUM'}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.sub)}</p><div class="learning-meta-v59"><span>${lock?'🔒 Premium':'🇲🇳 Монгол тайлбар'}</span><span>🎯 ЭЕШ focus</span></div><button class="primary-btn small" data-open="${x.id}">${lock?'🔒 Эрх нээх':'Хичээл үзэх'}</button></article>`}).join('');grid.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>open(b.dataset.open))}
function wordRows(a){return `<div class="lesson-word-list-v59">${(a||[]).map(w=>`<div><b>${esc(w[0])}</b><span>${esc(w[1])}<br><small>${esc(w[2]||'')}</small></span></div>`).join('')}</div>`}
function open(id){const x=lessons.find(z=>z.id===id);if(!x)return;if(locked(x)){showPaywall(x);return}let h=`<div class="lesson-breadcrumb-v59">${types[x.type]} • ${x.free?'Free lesson':'Premium lesson'}</div><h2>${esc(x.title)}</h2><p class="lesson-sub-v59">${esc(x.sub)}</p>`;if(x.sections)h+=x.sections.map((s,i)=>`<section class="human-section-v61"><h3>${i===0?'👩‍🏫 ':i===1?'🧩 ':i===2?'✏️ ':i===3?'⚠️ ':'🎯 '}${esc(s[0])}</h3><p>${esc(s[1]).replace(/\n/g,'<br>')}</p></section>`).join('');if(x.words)h+=`<section class="human-section-v61"><h3>📚 Үг + утга + хэрэглээ</h3>${wordRows(x.words)}</section><div class="lesson-tip-v59"><b>👩‍🏫 Багшийн зөвлөгөө</b><p>${esc(x.note||'')}</p></div>`;h+=`<div class="lesson-actions-v59"><button class="primary-btn" id="practice61">Practice хийх</button><button class="secondary-btn" id="done61">✓ Хичээлээ дуусгах</button></div>`;$('learningModalBodyV59').innerHTML=h;$('learningModalV59').classList.remove('hidden');$('practice61').onclick=()=>{try{localStorage.setItem('smarteshV59PracticeTopic',x.title)}catch(e){};$('learningModalV59').classList.add('hidden');if(window.showView)window.showView('practiceHub');else document.querySelector('[data-view="practiceHub"]')?.click()}}
function showPaywall(x){$('learningModalBodyV59').innerHTML=`<div class="paywall-v61"><div class="paywall-lock-v61">🔒</div><h2>${esc(x.title)}</h2><p>Энэ бол Premium хичээл. Ангилал бүрийн эхний 2 хичээлийг үнэгүй үзэж болно.</p><div class="paywall-prices-v61"><b>Student — 10,000₮ / 365 хоног</b><b>Teacher — 20,000₮ / 365 хоног</b></div><button class="primary-btn" id="goPremium61">Эрх авах</button><button class="secondary-btn" id="closePremium61">Үнэгүй хичээлүүд рүү буцах</button></div>`;$('learningModalV59').classList.remove('hidden');$('goPremium61').onclick=()=>{$('learningModalV59').classList.add('hidden');if(window.showView)window.showView('access');else document.querySelector('[data-view="access"]')?.click()};$('closePremium61').onclick=()=> $('learningModalV59').classList.add('hidden')}
$('learningTabsV59')?.querySelectorAll('[data-learn-type]').forEach(b=>b.onclick=()=>{type=b.dataset.learnType;$('learningTabsV59').querySelectorAll('button').forEach(z=>z.classList.toggle('active',z===b));render()});$('learningSearchV59')?.addEventListener('input',e=>{search=e.target.value;render()});$('learningCloseV59')?.addEventListener('click',()=> $('learningModalV59').classList.add('hidden'));$('learningModalV59')?.addEventListener('click',e=>{if(e.target.id==='learningModalV59')e.currentTarget.classList.add('hidden')});window.SmartESH_LearningV61={lessons,render,open};access();
})();
